---
version: '3.8'

services:
  app:
    image: caribou-app
    build:
      context: ./
      args:
        BUNDLE_WITHOUT: '' # keep empty
        RAILS_ENV: development
    command: app
    depends_on:
      - postgres
    volumes:
      - ./:/work
    ports:
      - 3000:3000

  # Misc Services

  postgres:
    image: public.ecr.aws/docker/library/postgres:14
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  vite:
    image: caribou-app
    command: ./bin/vite dev
    volumes:
      - source: ./
        target: /work
        type: bind
    ports:
      - 3036:3036
